---
- name: Collect system information from RHEL servers
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  gather_facts: yes

  tasks:
    - name: Gather facts from all RHEL servers
      ansible.builtin.setup:

    - name: Display relevant system information
      debug:
        msg: |
          System Information for Host: {{ ansible_hostname }}
          - Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - DNS Servers: {{ ansible_dns.nameservers }}
          - IP Address: {{ ansible_default_ipv4.address }}
          - Kernel: {{ ansible_kernel }}
          - Memory Installed: {{ ansible_memtotal_mb }} MB
          - Memory Swap: {{ ansible_swaptotal_mb }} MB
          - Processors: {{ ansible_processor_cores }}
          - Timezone: {{ ansible_facts['tz'] }}
